import pytest
import pandas as pd
import numpy as np
import subprocess
import os
import json

# Define paths and constants
BASE_DIR = os.path.dirname(__file__)
SCRIPT_PATH = os.path.join(BASE_DIR, "generate_geo_maps.py")
OUTPUT_DIR = os.path.join(BASE_DIR, "output")
REFERENCE_DIR = os.path.join(BASE_DIR, "reference_output") # Assuming a dir with golden files exists
FILE_LIST = [
    "Com_Cdiv_EMM_amy2018.csv", "Com_Cdiv_State_amy2018.csv",
    "Res_Cdiv_EMM_amy2018.csv", "Res_Cdiv_State_amy2018.csv"
]

@pytest.fixture(scope="module")
def run_generation_script():
    """Fixture to run the data generation script before tests."""
    # Ensure the output directory exists
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    # Run the script to generate all files
    # Using --force to ensure it runs even if files exist
    subprocess.run(
        ["python", SCRIPT_PATH, "--all", "--force"],
        check=True,
        capture_output=True,
        text=True
    )
    yield
    # Teardown: clean up generated files if necessary
    # for filename in os.listdir(OUTPUT_DIR):
    #     os.remove(os.path.join(OUTPUT_DIR, filename))


def test_file_generation(run_generation_script):
    """Test if all expected files are generated by the script."""
    generated_files = os.listdir(OUTPUT_DIR)
    
    # Check for energy files
    for f in FILE_LIST:
        assert f in generated_files, f"{f} was not generated."
    
    # Check for stock files
    for f in FILE_LIST:
        stock_file = f.replace(".csv", "_Stock.csv")
        assert stock_file in generated_files, f"{stock_file} was not generated."

    # Check for JSON files
    assert "mseg_res_com_emm_2024_tech_factors.json" in generated_files
    assert "mseg_res_com_state_2024_tech_factors.json" in generated_files


def compare_csv_files(file1_path, file2_path, tolerance=1e-6):
    """Helper function to compare two CSV files, checking for numeric differences."""
    df1 = pd.read_csv(file1_path)
    df2 = pd.read_csv(file2_path)

    # Basic checks
    assert df1.shape == df2.shape, f"Shape mismatch between {os.path.basename(file1_path)} and {os.path.basename(file2_path)}"
    assert df1.columns.equals(df2.columns), f"Column mismatch in {os.path.basename(file1_path)}"

    # Sort to ensure proper comparison
    sort_cols = ["End use", "CDIV"]
    df1 = df1.sort_values(by=sort_cols).reset_index(drop=True)
    df2 = df2.sort_values(by=sort_cols).reset_index(drop=True)

    # Compare non-numeric columns
    non_numeric_cols = df1.select_dtypes(exclude=np.number).columns
    pd.testing.assert_frame_equal(df1[non_numeric_cols], df2[non_numeric_cols])

    # Compare numeric columns with tolerance
    numeric_cols = df1.select_dtypes(include=np.number).columns
    pd.testing.assert_frame_equal(
        df1[numeric_cols], 
        df2[numeric_cols], 
        check_exact=False, 
        atol=tolerance, 
        rtol=tolerance
    )

# To use this test, you would need to create a `reference_output` directory
# and populate it with the "golden" versions of the output files.
# @pytest.mark.parametrize("filename", FILE_LIST)
# def test_csv_outputs_against_reference(run_generation_script, filename):
#     """Compares generated CSVs against a reference 'golden' version."""
#     # Compare energy file
#     generated_path = os.path.join(OUTPUT_DIR, filename)
#     reference_path = os.path.join(REFERENCE_DIR, filename)
#     assert os.path.exists(reference_path), f"Reference file not found: {reference_path}"
#     compare_csv_files(generated_path, reference_path)

#     # Compare stock file
#     stock_filename = filename.replace(".csv", "_Stock.csv")
#     generated_stock_path = os.path.join(OUTPUT_DIR, stock_filename)
#     reference_stock_path = os.path.join(REFERENCE_DIR, stock_filename)
#     assert os.path.exists(reference_stock_path), f"Reference file not found: {reference_stock_path}"
#     compare_csv_files(generated_stock_path, reference_stock_path)

# More tests can be added here to replicate the logic from the other notebooks,
# such as the JSON comparison and aggregation logic.
# For example, a test to validate the structure of the JSON output:

def validate_json_structure(file_path):
    """Helper to validate the basic structure of the output JSON."""
    with open(file_path, 'r') as f:
        data = json.load(f)
    
    assert isinstance(data, dict)
    # Example state, can be any state
    assert "CA" in data 
    # Example building type
    assert "single family home" in data["CA"]
    # Example fuel type
    assert "electricity" in data["CA"]["single family home"]
    # Example end use
    assert "cooling" in data["CA"]["single family home"]["electricity"]
    # Check for supply and tech splits
    cooling_data = data["CA"]["single family home"]["electricity"]["cooling"]
    assert "supply" in cooling_data
    assert "tech" in cooling_data
    # Check for energy and stock in a tech
    assert "energy" in cooling_data["tech"]["room ac"]
    assert "stock" in cooling_data["tech"]["room ac"]
    # Check for year data
    assert "2024" in cooling_data["tech"]["room ac"]["energy"]


@pytest.mark.parametrize("geography", ["emm", "state"])
def test_json_output_structure(run_generation_script, geography):
    """Tests the structure of the generated JSON files."""
    file_path = os.path.join(OUTPUT_DIR, f"mseg_res_com_{geography}_2024_tech_factors.json")
    assert os.path.exists(file_path)
    validate_json_structure(file_path)

# This is a starting point. The complex comparisons from the notebooks,
# especially the plotting, are better suited for manual validation or a more
# sophisticated visual regression testing framework. However, the underlying
# data comparison logic can be implemented here as demonstrated.
